Zap 61 main implementation
X-R-G-B/ZappyCulteur pull request #15
Opened 2023-05-29 22:26 UTC by KitetsuK

2023-05-30 23:36 UTC, Saverio976 requested changes
Alors, pourquoi le diff est aussi grand alors que sur dev y a plus des 3/4 de ces ajouts....

Une petite mise à jour de la branche est requise

2023-05-30 23:36 UTC, Saverio976 commented on src/AI/zappy_ai.py
>  #!/usr/bin/env python3
Pourquoi ce fichier est modifié ?

2023-05-30 23:36 UTC, Saverio976 commented on src/GUI/src/Main.cpp
> +    GUI::Main main;
Ça s'appelle du name shadowing et c'est mal

2023-05-30 23:36 UTC, Saverio976 commented on src/GUI/src/Parser.cpp
> +Parser::Parser()
Parser ?

2023-05-30 23:39 UTC, KitetsuK commented
Il y avait une aussi grande différence parce que comme on avait dit qu on faisait des rebase j'ai essayé et ca a mal tourné.

2023-05-30 23:40 UTC, KitetsuK commented on src/GUI/src/Main.cpp
> +    GUI::Main main;
On l'appelle App ca te va ?

2023-05-30 23:41 UTC, KitetsuK commented on src/GUI/src/Parser.cpp
> +Parser::Parser()
Ce ne sera plus Parser lorsque le CommandHandler sera merge sur ZAP-9-basic-gui

2023-05-30 23:48 UTC, Saverio976 commented on src/GUI/src/Main.cpp
> +    GUI::Main main;
C'est mieux

2023-06-05 01:59 UTC, TTENSHII commented
[Added]
- program arguments (-h and -p)
- improved app class
- now sends 'GRAPHIC' to the server on connection
- msz and pnw command support

2023-06-06 13:53 UTC, Saverio976 requested changes

2023-06-06 13:53 UTC, Saverio976 commented on src/GUI/src/App.cpp
> +        for (int i = 1; av[i] != nullptr; i++) {
alors, oui et non, pour une raison de compatibilité, je préfère tu fasse avec argc

2023-06-06 13:53 UTC, Saverio976 commented on src/GUI/src/App.cpp
> +        if (!strcmp(flag1.c_str(), "-h")) {
strcmp ?

2023-06-06 13:53 UTC, Saverio976 commented on src/GUI/src/App.cpp
> +        if (!strcmp(flag1.c_str(), "-p")) {
strcmp

2023-06-06 13:53 UTC, Saverio976 commented on src/GUI/src/App.cpp
> +        if (!strcmp(flag2.c_str(), "-h")) {
strcmp

2023-06-06 13:53 UTC, Saverio976 commented on src/GUI/src/App.cpp
> +        if (!strcmp(flag2.c_str(), "-p")) {
strcmp

2023-06-06 13:53 UTC, Saverio976 commented on src/GUI/src/App.cpp
> +            throw AppException("Args error : flags may be undefined");
AppArgsException (j'aime bien quand l'erreur est précise)

2023-06-06 13:53 UTC, Saverio976 commented on src/GUI/src/App.cpp
> +        if (!_port.empty() && !_ip.empty()) {
ducoup il se passe quoi si c'est empty ?
on va directement dans le try ?

(j'ai pas compris l'interêt de cette fonction)

2023-06-06 13:53 UTC, Saverio976 commented on src/GUI/src/App.cpp
> +            1920,
des valeurs magiques ?

2023-06-06 13:53 UTC, Saverio976 commented on src/GUI/src/App.cpp
> +            1080,
des valeurs magiques

2023-06-06 13:53 UTC, Saverio976 commented on src/GUI/src/App.cpp
> +            60,
des valeurs magiques ?

tu peux faire un static const dans le fichier si tu veux, ou un attribut

2023-06-06 13:53 UTC, Saverio976 commented on src/GUI/src/CommandHandler.cpp
> +        void CommandHandler::update(const std::vector<std::string>& commands)
```suggestion
        void CommandHandler::update(const std::vector<std::string> &commands)
```

2023-06-06 13:53 UTC, Saverio976 commented on src/GUI/src/CommandHandler.cpp
> +                _entityManager->killEntityById(id);
faites attention puisque les ID des player ça peut commencer à 0 ou 1 et aller aussi loin qu'on veut, vaut mieux que vous ajoutiez une string derrière genre 
`id + std::string("_player")` comme ça vous êtes sùr de pas détruire des trucs interne genre le floor ou jsp quoi

2023-06-06 13:53 UTC, Saverio976 commented on src/GUI/src/CommandHandler.hpp
> +            void update(const std::vector<std::string>& commands);
```suggestion
            void update(const std::vector<std::string> &commands);
```

2023-06-06 13:53 UTC, Saverio976 commented on src/GUI/src/CommandHandler.hpp
> +            bool setMapSize(const std::string& command);
```suggestion
            bool setMapSize(const std::string &command);
```

2023-06-06 13:53 UTC, Saverio976 commented on src/GUI/src/CommandHandler.hpp
> +            bool setNewPlayer(const std::string& command);
```suggestion
            bool setNewPlayer(const std::string &command);
```

2023-06-06 13:53 UTC, Saverio976 commented on src/GUI/src/CommandHandler.hpp
> +            const std::unordered_map<COMMAND_TYPE, std::function<bool(CommandHandler&, const std::string&)>> _toCall;
```suggestion
            const std::unordered_map<COMMAND_TYPE, std::function<bool(CommandHandler &, const std::string &)>> _toCall;
```

2023-06-06 13:53 UTC, Saverio976 commented on src/GUI/src/Main.cpp
> +    app(ac, av);
```suggestion
    returnValue = app(ac, av);
```

2023-06-06 14:55 UTC, KitetsuK commented on src/GUI/src/App.cpp
> +            throw AppException("Args error : flags may be undefined");
Non

2023-06-06 14:56 UTC, KitetsuK commented on src/GUI/src/App.cpp
> +        if (!_port.empty() && !_ip.empty()) {
Bah c'est pour soit on a pas d'arguments et on lance le main menu soit on a des arguments on lance le jeu direct.

2023-06-06 15:37 UTC, Saverio976 commented on src/GUI/src/App.cpp
> +            throw AppException("Args error : flags may be undefined");
ok

2023-06-06 15:44 UTC, TTENSHII commented on src/GUI/src/CommandHandler.cpp
> +                _entityManager->killEntityById(id);
ouais je pense que ca peut etre pas mal, j'ai mis floor_... pour le sol donc pourquoi pas faire pareil pour toutes les autres entitées

2023-06-06 19:35 UTC, Saverio976 requested changes

2023-06-06 19:35 UTC, Saverio976 commented on src/GUI/src/CommandHandler.cpp
> +        void CommandHandler::update(const std::vector<std::string>& commands)
```suggestion
        void CommandHandler::update(const std::vector<std::string> &commands)
```

2023-06-06 20:10 UTC, merged