Add tested pathFinding
X-R-G-B/ZappyCulteur pull request #19
Opened 2023-05-30 20:22 UTC by guillaumeAbel

2023-05-30 20:39 UTC, Saverio976 requested changes

2023-05-30 20:39 UTC, Saverio976 commented on src/AI/zappy_ia/IA.py
> +        resSetup = self.requestClient(self.teamName + "\n").split("\n")
Pourquoi avoir modifier ça ?

2023-05-30 20:39 UTC, Saverio976 commented on src/AI/zappy_ia/IA.py
> +    def pathFinding(self, pos: int):
Je ne comprends pas ce que fait cette fonction

2023-05-30 21:59 UTC, guillaumeAbel commented on src/AI/zappy_ia/IA.py
> +        resSetup = self.requestClient(self.teamName + "\n").split("\n")
on refait le meme code dans la fonction qui est appelée, ici et ailleur

2023-05-30 22:01 UTC, guillaumeAbel commented on src/AI/zappy_ia/IA.py
> +    def pathFinding(self, pos: int):
Quand l'ia look le server retourne un tableau et c'est cette fct qu'on appelera avec un int pour pour aller à une certaine case

2023-05-30 22:42 UTC, Saverio976 commented on src/AI/zappy_ia/IA.py
> +    def pathFinding(self, pos: int):
Il correspond à quoi cet int ?

2023-05-30 23:10 UTC, TTENSHII commented
👀 La norme de commit @guillaumeAbel

2023-05-30 23:37 UTC, Saverio976 commented
> 👀 La norme de commit @guillaumeAbel

Oui, j'avais pas vu, merci

Tu peux me fix ça @guillaumeAbel ?

2023-05-30 23:53 UTC, guillaumeAbel commented on src/AI/zappy_ia/IA.py
> +    def pathFinding(self, pos: int):
l'indice dans le tableau

2023-05-31 08:26 UTC, StEgo2103 approved these changes

2023-05-31 13:42 UTC, Saverio976 approved these changes

2023-05-31 13:44 UTC, Saverio976 requested changes
Il faut que tu me fix les commit

Utilise fit rebase -i HEAD~x

Modifie x avec le nombre de commit à modifier

2023-05-31 13:53 UTC, guillaumeAbel commented
> Il faut que tu me fix les commit
> 
> Utilise fit rebase -i HEAD~x
> 
> Modifie x avec le nombre de commit à modifier

j'essaie là

2023-05-31 14:33 UTC, Saverio976 approved these changes

2023-05-31 14:33 UTC, merged