Zap 63 method take food
X-R-G-B/ZappyCulteur pull request #22
Opened 2023-05-31 16:34 UTC by guillaumeAbel

2023-05-31 17:40 UTC, Saverio976 requested changes

2023-05-31 17:40 UTC, Saverio976 commented on src/AI/zappy_ia/IA.py
> +    def takeElementInLastLook(self, element: str):
Possibilité de transformer element en enum ?

2023-05-31 19:30 UTC, Saverio976 requested changes

2023-05-31 19:30 UTC, Saverio976 commented on src/AI/zappy_ia/IA.py
> +        self.mapSize: List[int] = [0, 0]
```suggestion
        self.mapSize: Tuple[int, int] = [0, 0]
```

2023-05-31 19:30 UTC, Saverio976 commented on src/AI/zappy_ia/IA.py
>  from typing import List
```suggestion
from typing import List, Tuple
```

2023-05-31 19:30 UTC, Saverio976 commented on src/AI/zappy_ia/IA.py
> +    def requestClient(self, command: str) -> str:
```suggestion
    def requestClient(self, command: Command, *args) -> str:
```

2023-05-31 19:30 UTC, Saverio976 commented on src/AI/zappy_ia/IA.py
> +        self.client.input(command)
```suggestion
        cmd = str(command)
        if len(args) != 0:
            cmd += " " + " ".join(args)
        self.client.input(cmd)
```

2023-05-31 19:30 UTC, Saverio976 commented on src/AI/zappy_ia/IA.py
> +            raise Exception("Server responsed ko to : " + str(command))
```suggestion
            raise Exception("Server responsed ko to : " + cmd)
```

2023-05-31 19:30 UTC, Saverio976 commented on src/AI/zappy_ia/IA.py
> +    Left = "Left\n"
```suggestion
    LEFT = "Left\n"
```

2023-05-31 19:30 UTC, Saverio976 commented on src/AI/zappy_ia/IA.py
> +                self.requestClient(Command.Left)
```suggestion
                self.requestClient(Command.LEFT)
```

2023-05-31 19:32 UTC, guillaumeAbel commented on src/AI/zappy_ia/IA.py
> +    def requestClient(self, command: str) -> str:
y'a pas de commandes avec des arguments

2023-05-31 19:43 UTC, guillaumeAbel commented on src/AI/zappy_ia/IA.py
> +                res[i].append(Element[elem])
non c'est bien les [] que je veux utilier ici

2023-06-01 12:24 UTC, Saverio976 approved these changes

2023-06-01 12:24 UTC, Saverio976 commented on src/AI/zappy_ia/IA.py
> +    TAKE_OBJECT = "Take object\n"
```suggestion
    TAKE_OBJECT = "Take"
```

2023-06-01 12:24 UTC, Saverio976 commented on src/AI/zappy_ia/IA.py
> +    SET_OBJECT = "Set object\n"
```suggestion
    SET_OBJECT = "Set"
```

2023-06-01 12:24 UTC, Saverio976 commented on src/AI/zappy_ia/IA.py
> +        self.client.input(command.value, arg)
ducoup si take / set ajouter un \n

2023-06-01 13:26 UTC, Saverio976 approved these changes

2023-06-01 13:26 UTC, merged