ZappyGui: add ebo edi and enw cmd
X-R-G-B/ZappyCulteur pull request #54
Opened 2023-06-09 23:07 UTC by TTENSHII

2023-06-09 23:22 UTC, Saverio976 requested changes

2023-06-09 23:22 UTC, Saverio976 commented on src/GUI/src/CommandHandler.cpp
> +            eggId = "Egg_" + eggId;
magick Egg

2023-06-09 23:22 UTC, Saverio976 commented on src/GUI/src/CommandHandler.cpp
> +            eggId = "Egg_" + eggId;
magick egg

2023-06-10 14:43 UTC, guillaumeAbel requested changes

2023-06-10 14:43 UTC, guillaumeAbel commented on src/GUI/src/Entities/Egg.hpp
> +                static constexpr char *eggPath = "src/GUI/assets/bees/egg.png";
that do warning

2023-06-10 14:43 UTC, guillaumeAbel commented on src/GUI/src/Entities/Egg.cpp
> +static const int eggSize = 42;
constexpr

2023-06-10 14:43 UTC, guillaumeAbel commented on src/GUI/src/Entities/Egg.hpp
> +                static constexpr char *eggPath = "src/GUI/assets/bees/egg.png";
et on est pas en c pas de char*

2023-06-10 14:43 UTC, guillaumeAbel commented on src/GUI/src/Entities/Egg.cpp
> +static const int eggSize = 42;
same for below lines

2023-06-10 16:10 UTC, guillaumeAbel approved these changes

2023-06-10 16:44 UTC, Saverio976 approved these changes

2023-06-12 14:33 UTC, Saverio976 approved these changes

2023-06-12 14:33 UTC, merged