ZappyServer: Add graphics cmd
X-R-G-B/ZappyCulteur pull request #72
Opened 2023-06-14 10:47 UTC by romainpanno

Commands :
 - pin
 - plv
 - sgt
 - sst
 - tna

And Fix graphic cmd ppo

2023-06-14 13:00 UTC, Saverio976 requested changes

2023-06-14 13:00 UTC, Saverio976 commented on src/SERVER/src/loop/state_connected/graphic_cmd/cmd_pin.c
> +    }
on est pas sensé envoyer quelque chose sur le buffer si jamais on envoi pas toutes la commande 👀

2023-06-14 13:00 UTC, Saverio976 commented on src/SERVER/src/loop/state_connected/graphic_cmd/cmd_tna.c
> +        circular_buffer_write(cl->write_to_outside, buff);
il faut faire ça queune fois par nom de team

là tu fais ça pour tous les trantorien

2023-06-14 15:03 UTC, guillaumeAbel approved these changes

2023-06-14 15:40 UTC, romainpanno commented on src/SERVER/src/loop/state_connected/graphic_cmd/cmd_pin.c
> +    }
`bool cmd_bct_x_y(zappy_t *zappy, ntw_client_t *cl, int x, int y)
{
    int i;

    if (x >= zappy->map->width || y >= zappy->map->height) {
        return false;
    }
    circular_buffer_write(cl->write_to_outside, "bct ");
    if (send_pos(zappy, cl, x, y) == false) {
        return false;
    }
    circular_buffer_write(cl->write_to_outside, " ");
    map_index_x_y_to_i(zappy->map, x, y, &i);
    send_ressources(zappy->map->tiles + i, cl);
    circular_buffer_write(cl->write_to_outside, "\n");
    return true;
}`

2023-06-14 15:42 UTC, romainpanno commented on src/SERVER/src/loop/state_connected/graphic_cmd/cmd_pin.c
> +    }
tu fasais ca sur bct jme suis dis que c'était bon

2023-06-14 15:43 UTC, romainpanno commented on src/SERVER/src/loop/state_connected/graphic_cmd/cmd_tna.c
> +        circular_buffer_write(cl->write_to_outside, buff);
ah ca contiens toutes les teams * le nombre de trantoriens ?

2023-06-15 12:15 UTC, Saverio976 approved these changes

2023-06-15 12:16 UTC, merged