Zap 114 end screen entity
X-R-G-B/ZappyCulteur pull request #99
Opened 2023-06-20 22:04 UTC by KitetsuK

2023-06-20 22:05 UTC, Saverio976 requested changes

2023-06-20 22:05 UTC, Saverio976 commented on src/GUI/assets/menu/VeryBeautifullSteve.png
Non

2023-06-20 22:06 UTC, guillaumeAbel approved these changes

2023-06-20 22:14 UTC, Saverio976 approved these changes

2023-06-20 22:58 UTC, Saverio976 commented
est ce que ça vous va la nouvelle image @KitetsuK  @TTENSHII  @guillaumeAbel  @StEgo2103  ?

2023-06-21 10:14 UTC, KitetsuK commented
> est ce que ça vous va la nouvelle image @KitetsuK  @TTENSHII  @guillaumeAbel  @StEgo2103  ?

Elle est pas belle

2023-06-21 13:44 UTC, merged